package com.example.electriccircuit.Components;

public class Capacitors {
}

// ADD CONNECTING INPUT
// ADD OUTPUT
// PROGRAM WIRES TO DO STUFF WITH INPUTS AND OUTPUTS
// PROGRAM WIRES TO HAVE JUNCTIONS FOR PARALLEL
// MAKE GRAPH LOGIC TO CALCULATE ALL VABIABLES